version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "<EXTERNAL LISTENING PORT>:80/tcp"
    environment:
      TZ: 'Europe/Zurich'
      WEBPASSWORD: '<PW>'
      DNS: '127.0.0.1'
    volumes:
      - '<CONFIG LOCATION ON RASPI>:/etc/pihole'
      - '<DNS CONFIG LOCATION ON RASPI>:/etc/dnsmasq.d'
    restart: unless-stopped
